export const mockData = [
  {
    id: 1,
    titlu: "Jante 100% originale",
    descriere:
      "Jante aduse de la o bunicuta din germania smr fata mea in puscarie daca mint",
    tip: "jante",
    marca: "bemveu",
    negociabil: "nu",
    locatie: "bucuresti",
    data_postare: "azi",
    stare: "nou",
    pret: "90",
  },
  {
    id: 2,
    titlu: "parbriz de tanc",
    descriere: "Lam adus din ucraina de pe un tanc",
    tip: "parbriz",
    marca: "dacia",
    negociabil: "da",
    locatie: "tecuci",
    data_postare: "in ultima saptamana",
    stare: "bulit rau",
    pret: "260",
  },
  {
    id: 3,
    titlu: "parbriz de tanc",
    descriere: "Lam adus din ucraina de pe un tanc",
    tip: "parbriz",
    marca: "dacia",
    negociabil: "da",
    locatie: "tecuci",
    data_postare: "in ultima saptamana",
    stare: "bulit rau",
    pret: "260",
  },
];
