export const mockedData = [
  {
    id: 1,
    title: "Culoare",
    options: [
      "Rosu",
      "Roz",
      "Negru",
      "Alb",
      "Auriu",
      "Verde",
      "Albastru",
      "Portocaliu",
      "Galben",
      "Violet",
      "Indigo",
      "Argintiu",
    ],
  },
  {
    id: 2,
    title: "Stare",
    options: ["Noua",
    "Buna",
    "Uzata"],
  },
  {
    id: 3,
    title: "Tipul produsului",
    options: [
      "Jante",
      "Roti",
      "Anvelope",
      "Piese Dezmembrare",
      "Bara",
      "Ventilator",
      "Aripa",
      "Capace",
      "Motor",
      "Planetara",
      "Centura",
      "Boxe",
      "Cutie de viteza",
      "Compresor",
      "Mocheta",
      "Filtru",
      "Amortizor",
      "Calculator / Computer",
      "Interior",
      "Scaune",
      "Alternator",
      "Turbina",
      "Conducta / Teava",
      "Airbag",
      "Incalzitor",
      "Usi",
      "Portbagaj",
      "Lumini",
      "Stergatoare",
      "Parbriz",
      "Aparatura de bord / Senzori",
      "KIT-uri",
      "Oglinda",
    ],
  },
  {
    id: 4,
    title: "An productie",
    options: ["1990-2000", "2000-2010", "2010-2020", "2020-prezent"],
  },
  {
    id: 5,
    title: "Marca",
    options: [
      "Seat",
      "Toyota",
      "Hyundai",
      "Renault",
      "Dacia",
      "Skoda",
      "Volkswagen",
      "Audi",
      "BMW",
      "Opel",
      "Mercedes-Benz",
      "Ford",
      "Citroen",
      "Honda",
      "Peugeot",
      "Fiat",
      "Ferrari",
      "Lamborghini",
      "Tesla",
      "Alfa Romeo",
      "Bugatti",
      "Jeep",
      "Land Rover",
      "Kia",
      "Mazda",
      "Nissan",
      "Saab",
      "Suzuki",
      "Volvo",
      "Yamaha",
      "Daewoo",
    ],
  },
  {
    id: 6,
    title: "Pret",
    options: ["0-100", "100-250", "250-500", "500-1000", "1000+"],
  },
  {
    id: 7,
    title: "Negociabil",
    options: ["da", "nu"],
  },
  {
    id: 8,
    title: "Data postarii",
    options: ["00:00-08:00", "08:01-16:00", "16:01-23:59"],
  },
  {
    id: 9,
    title: "Tipul carburantului",
    options: ["GPL",
    "Benzina",
    "Motorina"],
  },
];
